package com.kklabs.themoviedb.presentation.theme

import androidx.compose.ui.graphics.Color

object Colors {
    val disabledTextGrey: Color = Color(0xFFAAAAAA)
    val regentGray: Color = Color(0xFF8795A7)
    val jetGray: Color = Color(0xFF636F7E)
    val textColorNew: Color = Color(0xFF404040)
    val drGreyBorder: Color = Color(0xFFF1F4F6)
    val charcoalGrey: Color = Color(0xFF38424F)
    val charcoalGrey30: Color = Color(0x4D38424F)
    val black2d: Color = Color(0xFF2D2D2D)
    val p2pGrey: Color = Color(0xFFA5B6C5)
    val mgy65: Color = Color(0xFF808080)
    val blueOrchid: Color = Color(0xFF004DEC)
    val blueBlack: Color = Color(0xFF101C45)
    val gray: Color = Color(0xFF404040)
    val brightGray: Color = Color(0xFFECECEC)
    val dustyGrey: Color = Color(0xFF9A9A9A)
    val switchTailColor: Color = Color(0xFFE6E6E6)
    val white: Color = Color(0xFFFAFAFA)
    val white1: Color = Color(0XFFFFFFFF)
    val newGrey: Color = Color(0xFFE8ECEF)
    val gradientOne: Color = Color(0xFF2D51D1)
    val gradientTwo: Color = Color(0xFF4AC8DA)
    val disabledGrey: Color = Color(0xFFF4F8FB)
    val textNewGrey: Color = Color(0xFF999999)
    val greenishTeal: Color = Color(0xFF40BF7F)
    val greenCyan: Color = Color(0xFF339966)
    val azureBlue: Color = Color(0xFF6698FF)
    val pinkishRed2: Color = Color(0xFFD42B48)
    val pinkishRed: Color = Color(0xFFFF2171)
    val mbkBrown: Color = Color(0xFFB1903A)
    val mbkPink: Color = Color(0xFFFF5A5A)
    val cadetBlue: Color = Color(0xFFA5B3C5)
    val mbkLightYellow: Color = Color(0xFFFFF9E9)
    val borderBackgroundColor: Color = Color(0xFFF3F5F6)
    val orderItemBackground: Color = Color(0xFFF1FDFD)
    val orderItemBorder: Color = Color(0xFFE5F8F8)
    val orderItemBorderShadow: Color = Color(0xFFD4F2F9)
    val addNewAddressBorder: Color = Color(0xFFDDE4E9)
    val bgGreyColor: Color = Color(0xFFDDE4E9)
    val textGreyColor: Color = Color(0xFF9E9E9E)
    val transparent: Color = Color(0x00000000)
    val black: Color = Color(0xFF000000)
    val black40: Color = Color(0xFF000000).copy(alpha = 0.4f)
    val dashedColor: Color = Color(0xFFB3CBFF)
    val loanDueBG: Color = Color(0xFFF5F8FF)
    val loanTextColor: Color = Color(0xFF636F7E)
    val bgGrey: Color = Color(0xFFF7F8F9)
    val black2: Color = Color(0xFF292D32)
    val whiteDrift: Color = Color(0xFFF7F8F9)
    val lilyWhite: Color = Color(0xFFebf9fe)
    val lightCarminePinkColor: Color = Color(0xFFE4677C)
    val goldenText: Color = Color(0xFF956E22)
    val gradientStroke = Color(0xFFD6E0FC)
    val greyTint = Color(0xFF8A8A8A)
    val settlementAppBarColor = Color(0xFFECF9F2)
    val greenCircleColor = Color(0xFF37B34A)
    val yellowCircleColor = Color(0xFFECB833)
    val brightRed = Color(0xFFEC2B2B)
    val failedCircleColor = Color(0xFFFBE9EC)
    val initiatedCircleColor = Color(0xFFFBF5E9)
    val refundButtonColor = Color(0xFFAD1F36)
    val growBusinessGradient: Color = Color(0xFFECF7FF)
    val brandYellow: Color = Color(0xFFFFC300)
    val ltGrey: Color = Color(0xFFD9D9D9)
    val lightYellow: Color = Color(0xFFF7F1DE)
    val offWhite: Color = Color(0xFFF3F3F3)
    val yellowGrey: Color = Color(0xFFE5E3DB)
    val dirtyYellow: Color = Color(0xFF8A8261)
    val nomadGrey: Color = Color(0xFF637587)
    val borderGrey: Color = Color(0xFFAFAFAF)
    val indicatorGrey: Color = Color(0xFFD4D0C1)
    val textGreyNew: Color = Color(0xFFA7AAB7)
    val dangerRed: Color = Color(0xFFCF0000)

    val greyBd = Color(0xFF55635E)

    val textGrey = Color(0xFF464F4C)

    val brdGrey = Color(0xFFB3B3B3)
}